# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

jobs:
- job: ComingSoonApi

  pool:
    vmImage: 'windows-latest'

  variables:
    commingSoonApi: './GG.ComingSoon.Api.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/src/$(commingSoonApi)'

  - task: VSBuild@1
    displayName: Build ComingsoonApi
    inputs:
      solution: '**/src/$(commingSoonApi)'
      msbuildArgs: '/p:DeployOnBuild=true /p:OutDir=$(build.artifactStagingDirectory) /p:PackageAsSingleFile=false /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)" /p:DeployIisAppPath="Default Web Site"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - script: dir $(build.artifactStagingDirectory)

  - task: FileTransform@1
    displayName: Transform ComingsoonApi appsettings
    inputs:
      folderPath: '$(build.artifactStagingDirectory)'
      fileType: 'json'
      targetFiles: '**\appsettings.json'

  - task: PublishPipelineArtifact@1
    displayName: Publish ComingsoonApi artifact
    inputs:
      targetPath: '$(build.artifactStagingDirectory)'
      artifact: 'ComingsoonApi'
      publishLocation: 'pipeline'

- job: GiraffegramApi

  pool:
    vmImage: 'windows-latest'

  variables:
    giraffegramApi: './GG.Api.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/src/$(giraffegramApi)'

  - task: VSBuild@1
    displayName: Build GiraffegramApi
    inputs:
      solution: '**/src/$(giraffegramApi)'
      msbuildArgs: '/p:DeployOnBuild=true /p:OutDir=$(build.artifactStagingDirectory) /p:PackageAsSingleFile=false /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)" /p:DeployIisAppPath="Default Web Site"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - script: dir $(build.artifactStagingDirectory)

  - task: FileTransform@1
    displayName: Transform GiraffegramApi appsettings
    inputs:
      folderPath: '$(build.artifactStagingDirectory)'
      fileType: 'json'
      targetFiles: '**\appsettings.json'

  - task: PublishPipelineArtifact@1
    displayName: Publish GiraffegramApi artifact
    inputs:
      targetPath: '$(build.artifactStagingDirectory)'
      artifact: 'GiraffegramApi'
      publishLocation: 'pipeline'

- job: GiraffegramWeb

  pool:
    vmImage: 'windows-latest'

  steps:
  - task: Npm@1
    displayName: Install npm
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)\src\GG.UI'

  - task: Npm@1
    displayName: Build Giraffegram Web
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)\src\GG.UI'
      customCommand: 'run build'
  - task: PublishPipelineArtifact@1
    displayName: Publish Giraffegram Web artifact
    inputs:
      targetPath: '$(Build.SourcesDirectory)\src\GG.UI\dist\fuse'
      artifact: 'GiraffegramWeb'
      publishLocation: 'pipeline'
      
  
