// <auto-generated />
using System;
using GG.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GG.Migrations.MsSql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231230115325_FirstApplication")]
    partial class FirstApplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GG.Core.Entities.EmailHost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("UseSsl")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailHosts");
                });

            modelBuilder.Entity("GG.Core.Entities.EmailHostUser", b =>
                {
                    b.Property<Guid>("EmailHostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmailHostId", "UserId");

                    b.HasIndex(new[] { "EmailHostId" }, "IX_.EmailHostUser_.EmailHostId");

                    b.ToTable("EmailHostUsers");
                });

            modelBuilder.Entity("GG.Core.Entities.EmailHostUser", b =>
                {
                    b.HasOne("GG.Core.Entities.EmailHost", null)
                        .WithMany("EmailHostUsers")
                        .HasForeignKey("EmailHostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GG.Core.Entities.EmailHost", b =>
                {
                    b.Navigation("EmailHostUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
